language: node_js
node_js:
  - "8"

cache:
  yarn: true
  directories:
    "node_modules"

before_script:
  - yarn test && yarn lint

before_script:
  - yarn coveralls

deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_API_KEY"
  skip_cleanup: true
  on:
    branch: master
